config/routes.rb
Rails.application.routes.draw do
  resources :articles do
    resources :comments
  end
  root 'welcome#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
	has_many :comments
	validates :title, presence: true,
                    length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	def index
		@articles = Article.all
	end
	def new
		@article = Article.new
	end

	def create
		@article = Article.new(article_params)
		if @article.save
			redirect_to @article
		else
			render 'new'
		end
	end

	def show
	    @article = Article.find(params[:id])
	end

	def edit
		@article = Article.find(params[:id])
	end
	def update
		@article = Article.find(params[:id])
		if @article.update(article_params)
			redirect_to @article
		else
			render 'edit'
		end
	end
	def destroy 
		@article = Article.find(params[:id])
		@article.destroy
		redirect_to root_path
	end
	private
		def article_params
			params.require(:article).permit(:title, :text)
		end
	end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@article = Article.find(params[:article_id])
		@comment = @article.comments.create(comments_params)
		redirect_to article_path(@article)
	end

	private 
		def comments_params
			params.require(:comment).permit(:commenter, :body)
		end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		@articles = Article.all	
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/edit.html.erb
<div class="pages col-xs-9">
	<div class="row">
		<div class="col-xs-11">
			<div class="well page active">
				<h1 class="header">Editar Articulo</h1>
				<p>Aquí va cualquier clase de texto</p>
				<%= form_for :article, url: article_path(@article), class: 'form-horizontal', method: :patch  do |f| %>
					<% if @article.errors.any? %>
						Tienes <%= pluralize(@article.errors.count, "error") %>
						<% @article.errors.full_messages.each do |msg| %>
							<div class="alert alert-dismissible alert-warning">
								<button type="button" class="close" data-dismiss="alert">×</button>
								<p><%= msg %></p>
							</div>
						<% end %>
					<% end %>
				<fieldset>
					<div class="form-group">
						<%= f.label :title, 'Titulo', class: "col-xs-2 control-label", text: 'Titulo'  %>
						<div class="col-xs-10">
							<%= f.text_field :title, class: "form-control", placeholder: 'Titulo' %>	
						</div>
						
					</div>
					<div class="form-group">
						<%= f.label :text, 'Descripción', class: "col-xs-2 control-label" %>
						<div class="col-xs-10">
							<%= f.text_area :text, class: "form-control", rows: '3'%>
							<span class="help-block">Puedes desplazar el scroll del cuadro de texto para subir o bajar</span>
						</div>
							
					</div>
					<div class="form-group">
						<div class="col-xs-10">
							<%= link_to 'Back', articles_path, class: 'btn btn-primary' %>
							<%= f.submit class: "btn btn-primary" %>	
						</div>
					</div>
				</fieldset>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/articles/index.html.erb
<div class="pages col-xs-9">
	<div class="row">
		<div class="col-xs-11">
			<div class="well page active">
				<% @articles.each do |article| %>
				<div class="list-group">
					<div class="list-group-item">
				    	<div class="row-action-primary">
				      		<i class="material-icons">bookmark_border</i>
				    	</div>
				    	<div class="row-content">
				      		<div class="least-content">15m</div>
				      		<h4 class="list-group-item-heading"><%= article.title %></h4>
							<p class="list-group-item-text"><%= article.text %></p>
				    	</div>
				  	</div>
				  	<div class="list-group-separator"></div>
				</div>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/articles/new.html.erb
<div class="demo-card-wide mdl-card mdl-shadow--2dp">
	<div class="mdl-card__title">
		<h2 class="mdl-card__title-text">Nuevo Articulo</h2>
	</div>
	<div class="mdl-card__supporting-text">
		<%= form_for :article do |f| %>
			<div class="mdl-textfield mdl-js-textfield">
				<%= f.label :title, class: "mdl-textfield__label"  %>
				<%= f.text_field :title, class: "mdl-textfield__input"  %>
	</div><br />

	<div class="mdl-textfield mdl-js-textfield">
		<%= f.label :text, class: "mdl-textfield__label" %>
		<%= f.text_area :text, class: "mdl-textfield__input"%>
	</div>
	</div>
	<div class="mdl-card__actions mdl-card--border">
		<%= f.submit class: "mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect" %>
		<% end %>
	</div>
</div>

app/views/articles/show.html.erb
<div class="pages col-xs-9">
	<div class="row">
		<div class="col-xs-11">
			<div class="well page active">					
				<h1 class="header">
					<%= @article.title %> 
					<i class="material-icons"><%= link_to 'edit', edit_article_path(@article) %></i>
					<i class="material-icons"><%= link_to 'delete', article_path(@article), method: :delete, data: { confirm: 'Estás seguro?'} %></i>
				</h1>
				<p><%= @article.text %></p>
				<h2>Agrega un comentario</h2>
				<%= form_for([@article, @article.comments.build]) do |f| %>
					<fieldset>
						<div class="form-group">
							<%= f.label :commenter, 'Autor', class: "col-xs-2 control-label", text: 'Titulo'  %>
							<div class="col-xs-10">
								<%= f.text_field :commenter, class: "form-control", placeholder: 'Titulo' %>	
							</div>
							
						</div>
						<div class="form-group">
							<%= f.label :body, 'Cometario', class: "col-xs-2 control-label" %>
							<div class="col-xs-10">
								<%= f.text_area :body, class: "form-control", rows: '3'%>
								<span class="help-block">Puedes desplazar el scroll del cuadro de texto para subir o bajar</span>
							</div>
								
						</div>
						<div class="form-group">
							<div class="col-xs-10">
								<%= f.submit class: "btn btn-primary" %>	
							</div>
						</div>
					</fieldset>
					<h3>Comentarios</h3>
					<div class="list-group">
						<% @article.comments.each do |comment| %>
							<div class="list-group-item">
								<div class="row-picture">
									<% if comment.body? %>
									<img class="circle" src="http://lorempixel.com/56/56/people/1" alt="icon">
									<% end %>
								</div>
								<div class="row-content">
									<h4 class="list-group-item-heading"><%= comment.commenter %></h4>
									<p class="list-group-item-text"><%= comment.body %></p>
								</div>
							</div>
							<div class="list-group-separator"></div>
						<% end %>
					</div>
				<% end %>
				<%= link_to 'Back', root_path, class: 'btn btn-primary' %>
			</div>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Andrés Arias Rauld</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	  <%= stylesheet_link_tag "https://fonts.googleapis.com/icon?family=Material+Icons" %>
	</head>
	<body>
		<div class="header-panel shadow-z-2">
			<div class="container-fluid">
				<div class="row">
					<div class="col-xs-3">
						<h1>Andrés<br />Arias Rauld</h1>
					</div>
				</div>
			</div>
		</div>
		<div class="container-fluid main">
			<div class="row">
				<nav class="col-xs-3 menu">
					<ul>
						<li class="withripple active" data-target="#inicio">
							Inicio
							<div class="ripple-container"></div>
						</li>
						<li class="withripple" data-target="#proyectos">
							Proyectos
							<div class="ripple-container"></div>
						</li>
						<li class="withripple" data-target="#screencast">
							ScreenCast
							<div class="ripple-container"></div>
						</li>
						<li class="withripple" data-target="#about">
							Sobre mi...
							<div class="ripple-container"></div>
						</li>
					</ul>
				</nav>
				<%= yield %>
			</div>
			<script>
			  window.page = window.location.hash || "#inicio";

			  $(document).ready(function () {
			    if (window.page != "#inicio") {
			      $(".menu").find("li[data-target=" + window.page + "]").trigger("click");
			    }
			  });

			  $(window).on("resize", function () {
			    $("html, body").height($(window).height());
			    $(".main, .menu").height($(window).height() - $(".header-panel").outerHeight());
			    $(".pages").height($(window).height());
			  }).trigger("resize");

			  $(".menu li").click(function () {
			    // Menu
			    console.log($(this).data("target"));
			    if (!$(this).data("target")) return;
			    if ($(this).is(".active")) return;
			    $(".menu li").not($(this)).removeClass("active");
			    $(".page").not(page).removeClass("active").hide();
			    window.page = $(this).data("target");
			    var page = $(window.page);
			    window.location.hash = window.page;
			    $(this).addClass("active");


			    page.show();

			    var totop = setInterval(function () {
			      $(".pages").animate({scrollTop: 0}, 0);
			    }, 1);

			    setTimeout(function () {
			      page.addClass("active");
			      setTimeout(function () {
			        clearInterval(totop);
			      }, 1000);
			    }, 100);
			  });

			  function cleanSource(html) {
			    var lines = html.split(/\n/);

			    lines.shift();
			    lines.splice(-1, 1);

			    var indentSize = lines[0].length - lines[0].trim().length,
			        re = new RegExp(" {" + indentSize + "}");

			    lines = lines.map(function (line) {
			      if (line.match(re)) {
			        line = line.substring(indentSize);
			      }

			      return line;
			    });

			    lines = lines.join("\n");

			    return lines;
			  }

			  $("#opensource").click(function () {
			    $.get(window.location.href, function (data) {
			      var html = $(data).find(window.page).html();
			      html = cleanSource(html);
			      $("#source-modal pre").text(html);
			      $("#source-modal").modal();
			    });
			  });
			</script>
		</div>
	</body>
</html>

app/views/welcome/index.html.erb
	<div class="pages col-xs-9">
		<div class="row">
			<div class="col-xs-11">
				<div class="well page active" id="inicio">
					<h1 class="header">Bienvenidos</h1>
					<p>Aquí va cualquier clase de texto</p>
					<% @articles.each do |article| %>
					<div class="list-group">
						<div class="list-group-item">
					    	<div class="row-action-primary">
					      		<i class="material-icons"><%= link_to 'bookmark_border', article %></i>
					    	</div>
					    	<div class="row-content">
					      		<div class="least-content"><%= time_ago_in_words(article.created_at) %></div>
					      		<h4 class="list-group-item-heading"><%= link_to article.title, article %></h4>
								<p class="list-group-item-text"><%= article.text %></p>
					    	</div>
					  	</div>
					  	<div class="list-group-separator"></div>
					</div>
					<% end %>
				</div>
				<!-- Proyectos -->
				<div class="well page" id="proyectos" style="display:none;">
					<h1 class="header">Proyectos</h1>
					<p>Listado de Proyectos o colaboraciones realizadas por mi</p>
					<div class="list-group">
						<div class="list-group-item">
							<div class="row-action-primary">
								<i class="material-icons">folder</i>
							</div>
							<div class="row-content">
								<div class="action-secondary">
									<i class="material-icons"><%= link_to 'backup', 'https://github.com/AndresAR/Odonmed', {'target' => '_blank'}%></i>
								</div>
								<h4 class="list-group-item-heading">OdonMed</h4>
								<p class="list-group-item-text">Sistema de administración y gestión de pacientes</p>
							</div>
						</div>
						<div class="list-group-separator"></div>
						<div class="list-group-item">
							<div class="row-action-primary">
								<i class="material-icons">folder</i>
							</div>
							<div class="row-content">
								<div class="action-secondary">
									<i class="material-icons">
										<%= link_to 'backup', 'https://github.com/AndresAR/Vademecum', {'target' => '_blank'}%>
									</i>
								</div>
								<h4 class="list-group-item-heading">Vademecum</h4>
								<p class="list-group-item-text">Listado de medicamentos, en donde podrás encontrar forma de uso, dosis entre otros.</p>
							</div>
						</div>
						<div class="list-group-separator"></div>
						<div class="list-group-item">
							<div class="row-action-primary">
								<i class="material-icons">folder</i>
							</div>
							<div class="row-content">
								<div class="action-secondary">
									<i class="material-icons">
										<%= link_to 'backup', 'http://www.radioclandestina.cl', {'target' => '_blank'}%>
									</i>
								</div>
								<h4 class="list-group-item-heading">RadioClandestina</h4>
								<p class="list-group-item-text">Sitio Web de Radio por streaming, el proyecto actualmente cumple más de 10 años de vida</p>
							</div>
						</div>
						<div class="list-group-separator"></div>
					</div>
				</div>
				
				<!-- ScreenCast -->
				<div class="well page" id="screencast" style="display:none;">
					<h1 class="header">ScreenCast</h1>
					<p>Aquí va cualquier clase de texto</p>
					<div class="list-group">
						<div class="list-group-item">
							<div class="row-picture">
								<img class="circle" src="http://restrack.me/images/rails-logo.png" alt="icon">
							</div>
							<div class="row-content">
								<h4 class="list-group-item-heading">Blog</h4>
								<p class="list-group-item-text">Sitio para entender el funcionamiento y programación con el FrameWork Ruby on Rails</p>
							</div>
						</div>
						<div class="list-group-separator"></div>
					</div>
				</div>

				<!-- Sobre mi -->
				<div class="well page" id="about" style="display:none;">
					<h1 class="header">Sobre mi...</h1>
					<p>
						Nacido en Santiago de Chile, soy Ingeniero en Informática desarrollador desde temprana edad, amante del Back-End y el asincronismo.
					</p>
					<p>
						La programación es la expresión máxima de liberación para los que nos dedicamos a esto, podemos convertir una idea en algo real, poder realizar un proyecto de inicio a fin, aprendiendo en el camino, desarrollando nuevas ideas, siempre en busca de entregar lo mejor de de ti.
					</p>
					<p>
						La integración del FronEnd con el BackEnd en busca de la resolución de problemas para los usuarios, una interfaz amigable, una base robusta, bajo tiempo de respuesta en las interacciones. Estos detalles hacer de la programación algo emocionante.
					</p>
					<p>
						Poder enseñar lo que sé es algo que también me apasiona, quizás cuando inicie en esta loca aventura no habia mucho de donde conseguir ideas, ahora con la llegada de la internet y las nuevas tecnologías es más fácil para los que recién empiezan buscar información o ideas para poder desarrollar o aprender, es por lo mismo que el contenido que pudiese entender no será siguiendo una guía sino que será en base a mi experiencia en mis años desarrollando, es por lo mismo que existe una sección de ScreenCast, donde mostraré como voy desarrollando la idea.
					</p>
				</div>
			</div>
		</div>
	</div>